### ISSUE TITLE
Unable to correctly test access to ClearanceLevels due to code mismatch?

### ISSUE THREAD

**Issue by jsgitit** [shenanigan/fbi-demo#1]
Hello, 

Thank you for publishing https://www.freecodecamp.org/news/authenticate-and-authorize-apis-in-dotnet5/

I tried to follow along in the example in that page, however, I was not able to see the "Public Files Accessed" or "Classified Files Accessed".  As a result, I'm unable to complete my understanding of this security model.

When I compared your repo to mine, it was different in the AdminController.  This controller is also different when compared to the page, so I'm uncertain which is correct.  Is this repo matching the page article contents?  For example, I have "GenerateBadge()", not "EnrolAgent()".  

Will an update to the article or repo be coming soon? Thanks!

**Comment by shenanigan** [comment]
Hi @jsgitit,
Sorry for the confusion. I have renamed EnrolAgent to GenerateBadge in the repository. This function generates a bearer token for the Agent. You can find the updated article here: https://arjavdave.com/2021/03/31/net-5-setup-authentication-and-authorisation/ 

I have also requested freecodecamp to update the article.

You can find methods for accessing public and classified files in **AgentController.cs** file, since they are actions related to an Agent.
